/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author Saivignesh Sridhar
 */
public class DemoViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemoViewPanel
     */
    Person person;
    public DemoViewPanel(Person person) {
        initComponents();
        
        this.person = person;
        displayDemoDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDemoTitle = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMobNo = new javax.swing.JLabel();
        FtxtMobileNo = new javax.swing.JFormattedTextField();
        lblDob = new javax.swing.JLabel();
        FtxtDob = new javax.swing.JFormattedTextField();
        lblAge = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();

        setBackground(new java.awt.Color(222, 236, 236));
        setForeground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(673, 436));

        jPanel1.setBackground(new java.awt.Color(222, 236, 236));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setName(""); // NOI18N

        lblDemoTitle.setBackground(new java.awt.Color(222, 236, 236));
        lblDemoTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblDemoTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblDemoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDemoTitle.setText("Demographic Details");

        txtFirstName.setEditable(false);
        txtFirstName.setBackground(new java.awt.Color(222, 236, 236));
        txtFirstName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 102, 102));
        txtFirstName.setToolTipText("First Name");
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblFirstName.setBackground(new java.awt.Color(222, 236, 236));
        lblFirstName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(0, 102, 102));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstName.setText("First Name");

        lblLastName.setBackground(new java.awt.Color(222, 236, 236));
        lblLastName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 102, 102));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastName.setText("Last Name");

        txtLastName.setEditable(false);
        txtLastName.setBackground(new java.awt.Color(222, 236, 236));
        txtLastName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 102, 102));
        txtLastName.setToolTipText("Last Name");
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblMobNo.setBackground(new java.awt.Color(222, 236, 236));
        lblMobNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMobNo.setForeground(new java.awt.Color(0, 102, 102));
        lblMobNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMobNo.setText("Mobile Number");

        FtxtMobileNo.setEditable(false);
        FtxtMobileNo.setBackground(new java.awt.Color(222, 236, 236));
        FtxtMobileNo.setForeground(new java.awt.Color(0, 102, 102));
        FtxtMobileNo.setToolTipText("Mobile Number");
        FtxtMobileNo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FtxtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtxtMobileNoActionPerformed(evt);
            }
        });

        lblDob.setBackground(new java.awt.Color(222, 236, 236));
        lblDob.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblDob.setForeground(new java.awt.Color(0, 102, 102));
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob.setText("DOB (MM/DD/YYYY)");

        FtxtDob.setEditable(false);
        FtxtDob.setBackground(new java.awt.Color(222, 236, 236));
        FtxtDob.setForeground(new java.awt.Color(0, 102, 102));
        FtxtDob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        FtxtDob.setToolTipText("Mobile Number");
        FtxtDob.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        FtxtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtxtDobActionPerformed(evt);
            }
        });

        lblAge.setBackground(new java.awt.Color(222, 236, 236));
        lblAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 102, 102));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAge.setText("Age");

        lblHeight.setBackground(new java.awt.Color(222, 236, 236));
        lblHeight.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(0, 102, 102));
        lblHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeight.setText("Height");

        lblWeight.setBackground(new java.awt.Color(222, 236, 236));
        lblWeight.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(0, 102, 102));
        lblWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeight.setText("Weight");

        lblSSN.setBackground(new java.awt.Color(222, 236, 236));
        lblSSN.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(0, 102, 102));
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSSN.setText("Social Security Number");

        txtSSN.setEditable(false);
        txtSSN.setBackground(new java.awt.Color(222, 236, 236));
        txtSSN.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(0, 102, 102));
        txtSSN.setToolTipText("First Name");
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(222, 236, 236));
        txtAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(0, 102, 102));
        txtAge.setToolTipText("How old you are");
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtHeight.setEditable(false);
        txtHeight.setBackground(new java.awt.Color(222, 236, 236));
        txtHeight.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(0, 102, 102));
        txtHeight.setToolTipText("How old you are");
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        txtWeight.setEditable(false);
        txtWeight.setBackground(new java.awt.Color(222, 236, 236));
        txtWeight.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(0, 102, 102));
        txtWeight.setToolTipText("How old you are");
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDemoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMobNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWeight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLastName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtFirstName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FtxtDob)
                                    .addComponent(FtxtMobileNo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDemoTitle)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FtxtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob)
                    .addComponent(FtxtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void FtxtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtxtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FtxtDobActionPerformed

    private void FtxtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtxtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FtxtMobileNoActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtDob;
    private javax.swing.JFormattedTextField FtxtMobileNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDemoTitle;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobNo;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void displayDemoDetails() {
        if(! (person.getStSSN() == null) ){
      txtFirstName.setText(person.getStFirstName());
      txtLastName.setText(person.getStLastName());
      txtAge.setText(String.valueOf(person.getInAge()));
      txtHeight.setText(String.valueOf(person.getInHeight()));
      txtWeight.setText(String.valueOf(person.getInWeight()));
      FtxtDob.setText(person.getStDOB());
      FtxtMobileNo.setText(person.getStMobNo());
      txtSSN.setText(person.getStSSN());
        } else{
            JOptionPane.showMessageDialog(this, "Kindly check if the Personal Details are properly Submitted.","Warning : Missing Information",2);
        }      
      
    }
}
