/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author Saivignesh Sridhar
 */
public class MedViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedViewPanel
     */
    Person person;
    public MedViewPanel(Person person) {
        initComponents();
        this.person = person;
        displayMedical();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedTitle = new javax.swing.JLabel();
        lblMedRecNo = new javax.swing.JLabel();
        txtMedRecNo = new javax.swing.JTextField();
        lblAllergy1 = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtAllergy3 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        txtAllergy1 = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 236, 236));
        setForeground(new java.awt.Color(0, 102, 102));

        lblMedTitle.setBackground(new java.awt.Color(222, 236, 236));
        lblMedTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMedTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblMedTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedTitle.setText("Medical Details");

        lblMedRecNo.setBackground(new java.awt.Color(222, 236, 236));
        lblMedRecNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMedRecNo.setForeground(new java.awt.Color(0, 102, 102));
        lblMedRecNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedRecNo.setText("Medical Record Number");

        txtMedRecNo.setEditable(false);
        txtMedRecNo.setBackground(new java.awt.Color(222, 236, 236));
        txtMedRecNo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtMedRecNo.setForeground(new java.awt.Color(0, 102, 102));
        txtMedRecNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecNoActionPerformed(evt);
            }
        });

        lblAllergy1.setBackground(new java.awt.Color(222, 236, 236));
        lblAllergy1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAllergy1.setForeground(new java.awt.Color(0, 102, 102));
        lblAllergy1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAllergy1.setText("Allergy 1");

        lblAllergy2.setBackground(new java.awt.Color(222, 236, 236));
        lblAllergy2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAllergy2.setForeground(new java.awt.Color(0, 102, 102));
        lblAllergy2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAllergy2.setText("Allergy 2");

        lblAllergy3.setBackground(new java.awt.Color(222, 236, 236));
        lblAllergy3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAllergy3.setForeground(new java.awt.Color(0, 102, 102));
        lblAllergy3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAllergy3.setText("Allergy 3");

        txtAllergy3.setEditable(false);
        txtAllergy3.setBackground(new java.awt.Color(222, 236, 236));
        txtAllergy3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtAllergy3.setForeground(new java.awt.Color(0, 102, 102));
        txtAllergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy3ActionPerformed(evt);
            }
        });

        txtAllergy2.setEditable(false);
        txtAllergy2.setBackground(new java.awt.Color(222, 236, 236));
        txtAllergy2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtAllergy2.setForeground(new java.awt.Color(0, 102, 102));
        txtAllergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy2ActionPerformed(evt);
            }
        });

        txtAllergy1.setEditable(false);
        txtAllergy1.setBackground(new java.awt.Color(222, 236, 236));
        txtAllergy1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtAllergy1.setForeground(new java.awt.Color(0, 102, 102));
        txtAllergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy1ActionPerformed(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(222, 236, 236));
        lblName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 102));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name");

        lblAge.setBackground(new java.awt.Color(222, 236, 236));
        lblAge.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 102, 102));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAge.setText("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMedTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAllergy2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(lblAllergy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(177, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedRecNo))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAllergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAllergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedRecNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecNoActionPerformed

    private void txtAllergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy3ActionPerformed

    private void txtAllergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy2ActionPerformed

    private void txtAllergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblMedRecNo;
    private javax.swing.JLabel lblMedTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtMedRecNo;
    // End of variables declaration//GEN-END:variables

    private void displayMedical() {
        try{
        lblName.setText(person.getStLastName()+", "+person.getStFirstName());
        lblAge.setText(String.valueOf(person.getInAge())+" y.o.");
        txtMedRecNo.setText(person.getMedical().getStMedRecNo());
        txtAllergy1.setText(person.getMedical().getStAllergy1());
        txtAllergy2.setText(person.getMedical().getStAllergy2());
        txtAllergy3.setText(person.getMedical().getStAllergy3());
        } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Kindly check if the Address Details are properly Submitted.","Warning : Missing Information",2);
        }
    }
}
