/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class ViewUpdateDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdateDeliveryManJPanel
     */
    public JPanel container;
    public DeliveryMan deliveryMan;
    public DeliveryManDirectory deliveryManDirectory;
    private final EcoSystem system;
    private String currentPhoneNo;
    private String currentMailID;
    
    
    public ViewUpdateDeliveryManJPanel(EcoSystem system, JPanel container, DeliveryMan deliveryMan, DeliveryManDirectory deliveryManDirectory) {
        initComponents();
        this.container = container;
        this.deliveryMan = deliveryMan;
        this.deliveryManDirectory = deliveryManDirectory;
        this.system = system;
        this.currentMailID = deliveryMan.getDeliEmail();
        this.currentPhoneNo = deliveryMan.getDeliPhoneNo();
        
        txtDeliNo.setText(deliveryMan.getDeliveryID());
        txtDeliName.setText(deliveryMan.getDeliName());
        txtDeliContact.setText(deliveryMan.getDeliPhoneNo());
        txtDeliEmail.setText(deliveryMan.getDeliEmail());
        disableEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeliEmail = new javax.swing.JLabel();
        lblDeliContact = new javax.swing.JLabel();
        txtDeliContact = new javax.swing.JTextField();
        txtDeliName = new javax.swing.JTextField();
        txtDeliNo = new javax.swing.JTextField();
        lblDeliName = new javax.swing.JLabel();
        lblDeliNo = new javax.swing.JLabel();
        txtDeliEmail = new javax.swing.JTextField();
        lblAddDeli = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnEnableUpdate = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();

        lblDeliEmail.setText("Email ID :");

        lblDeliContact.setText("Contact No :");

        lblDeliName.setText("Full Name :");

        lblDeliNo.setText("Username :");

        lblAddDeli.setText("Add Delivery Person");

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnEnableUpdate.setText("Enable Update");
        btnEnableUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUpdateActionPerformed(evt);
            }
        });

        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDeliEmail)
                            .addComponent(lblDeliName)
                            .addComponent(lblDeliContact)
                            .addComponent(lblDeliNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeliEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtDeliName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeliContact)
                            .addComponent(txtDeliNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack1)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnableUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddDeli)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblAddDeli)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliNo)
                    .addComponent(txtDeliNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliName)
                    .addComponent(txtDeliName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeliEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeliContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeliContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnableUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnBack1))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDeliveryManJPanel manageDeliJPanel = (ManageDeliveryManJPanel) component;
        manageDeliJPanel.populateDeliveryManTable();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_btnBack1ActionPerformed
    public void disableEdit() {
        txtDeliNo.setEditable(false);
        txtDeliName.setEditable(false);
        txtDeliContact.setEditable(false);
        txtDeliEmail.setEditable(false);
    }
    private void btnEnableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUpdateActionPerformed
        // TODO add your handling code here:
        txtDeliName.setEditable(true);
        txtDeliContact.setEditable(true);
        txtDeliEmail.setEditable(true);
     
        btnEnableUpdate.setEnabled(false);
    }//GEN-LAST:event_btnEnableUpdateActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        String custID = txtDeliNo.getText();
        String custName = txtDeliName.getText();
        String custContact = txtDeliContact.getText();
        String custEmail = txtDeliEmail.getText();
        boolean allSet = true;

        if( custName.isEmpty() || custContact.isEmpty() || custEmail.isEmpty() ) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }   else if (!system.validateEmail(custEmail)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly check the entered Email ID format.");
        }   else if (!deliveryManDirectory.isEmailUnique(custEmail)) {
            if(!currentMailID.equals(currentMailID))
            {
                allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Email ID is already mapped to another Customer.");
            }
        }
        if (!deliveryManDirectory.isContactNoUnique(custContact)) {
            if(!currentPhoneNo.equals(custContact)){
                allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Customer.");
            }
        }
        if(allSet == true){
            deliveryManDirectory.updateDeliveryMan(custID, custName, custContact, custEmail);
            JOptionPane.showMessageDialog(null, "Customer details updated!");
            disableEdit();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnEnableUpdate;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel lblAddDeli;
    private javax.swing.JLabel lblDeliContact;
    private javax.swing.JLabel lblDeliEmail;
    private javax.swing.JLabel lblDeliName;
    private javax.swing.JLabel lblDeliNo;
    private javax.swing.JTextField txtDeliContact;
    private javax.swing.JTextField txtDeliEmail;
    private javax.swing.JTextField txtDeliName;
    private javax.swing.JTextField txtDeliNo;
    // End of variables declaration//GEN-END:variables
}
