/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliverManDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Host.HostDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class ManageDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryManJPanel
     */
    JPanel container;
    EcoSystem system;
    HostDirectory hostDirectory;
    RestaurantDirectory restaurantDirectory;
    DeliverManDirectory deliveryManDirectory;
    
    public ManageDeliveryManJPanel(JPanel container, EcoSystem system, DeliverManDirectory deliveryManDirectory) {
        initComponents();
        this.container = container;
        this.system = system;
        this.deliveryManDirectory = deliveryManDirectory;
        populateDeliveryManTable();
    }
public void populateDeliveryManTable() {
        DefaultTableModel model = (DefaultTableModel) JTblDeliveyMan.getModel();
        
        model.setRowCount(0);
        for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {
            for (DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManDirectory()) {
                if (deliveryMan.getDeliveryID().equalsIgnoreCase(ua.getEmployee().getName())) {
                    Object[] row = new Object[5];
                    row[0] = deliveryMan.getDeliveryID();
                    row[1] = deliveryMan.getDeliName();
                    row[2] = ua.getUsername();
                    row[3] = deliveryMan.getDeliPhoneNo();
                    row[4] = deliveryMan.getDeliEmail();
                    
                    model.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_DeliDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblDeliveyMan = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAddDeli = new javax.swing.JButton();
        btnViewDeli = new javax.swing.JButton();
        btnDelDeli = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lbl_DeliDetails.setBackground(new java.awt.Color(204, 255, 255));
        lbl_DeliDetails.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lbl_DeliDetails.setForeground(new java.awt.Color(0, 51, 51));
        lbl_DeliDetails.setText("Delivery Men Database");

        JTblDeliveyMan.setBackground(new java.awt.Color(204, 255, 255));
        JTblDeliveyMan.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        JTblDeliveyMan.setForeground(new java.awt.Color(0, 51, 51));
        JTblDeliveyMan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Delivery Man No", "Name", "User Name", "Contact No", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblDeliveyMan);

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddDeli.setBackground(new java.awt.Color(204, 255, 255));
        btnAddDeli.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddDeli.setForeground(new java.awt.Color(0, 51, 51));
        btnAddDeli.setText("Add Delivery Man");
        btnAddDeli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddDeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeliActionPerformed(evt);
            }
        });

        btnViewDeli.setBackground(new java.awt.Color(204, 255, 255));
        btnViewDeli.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnViewDeli.setForeground(new java.awt.Color(0, 51, 51));
        btnViewDeli.setText("View Delivery Man");
        btnViewDeli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeliActionPerformed(evt);
            }
        });

        btnDelDeli.setBackground(new java.awt.Color(204, 255, 255));
        btnDelDeli.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnDelDeli.setForeground(new java.awt.Color(0, 51, 51));
        btnDelDeli.setText("Delete Delivery Man");
        btnDelDeli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelDeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lbl_DeliDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewDeli, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(btnAddDeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55)
                                .addComponent(btnDelDeli, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_DeliDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnAddDeli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewDeli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnDelDeli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnBack)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeliActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddDeliveryManJPanel addDeliJPanel = new AddDeliveryManJPanel(container, system, deliveryManDirectory);
        container.add(addDeliJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnAddDeliActionPerformed

    private void btnViewDeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeliActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTblDeliveyMan.getSelectedRow();
        int count = JTblDeliveyMan.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                CardLayout layout = (CardLayout) container.getLayout();
                DeliveryMan deli = deliveryManDirectory.getDeliveryManById(selectedRow);
                ViewUpdateDeliveryManJPanel viewUpdateRestPanel = new ViewUpdateDeliveryManJPanel(system, container, deli, deliveryManDirectory);
                container.add(viewUpdateRestPanel);
                layout.next(container);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnViewDeliActionPerformed

    private void btnDelDeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDeliActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTblDeliveyMan.getSelectedRow();
        int count = JTblDeliveyMan.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
                if (selectionResult == JOptionPane.YES_OPTION) {
                    deliveryManDirectory.deleteDeliveryMan(selectedRow, system);
//                    populateRestaurantsTable();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnDelDeliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTblDeliveyMan;
    private javax.swing.JButton btnAddDeli;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelDeli;
    private javax.swing.JButton btnViewDeli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_DeliDetails;
    // End of variables declaration//GEN-END:variables
}
