/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Saivignesh Sridhar
 */
public class AddCustomerJPanel extends javax.swing.JPanel {

    private CustomerDirectory custDirectory;
    private JPanel container;
    private EcoSystem system;
    
    Customer cust = new Customer();
    /**
     * Creates new form AddCustomerJPanel
     */
    public AddCustomerJPanel(JPanel container, EcoSystem system, CustomerDirectory custDir) {
        initComponents();
        this.custDirectory = custDir;
        this.system = system;
        this.container = container;
        System.out.println("-- "+system);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCustomer = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        lblCustUserName = new javax.swing.JLabel();
        lblCustPass = new javax.swing.JLabel();
        lblCustContact = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        txtCustUserName = new javax.swing.JTextField();
        txtCustContact = new javax.swing.JTextField();
        lblCustEmail = new javax.swing.JLabel();
        txtCustEmail = new javax.swing.JTextField();
        pbCustPassStr = new javax.swing.JProgressBar();
        lblCustAddr = new javax.swing.JLabel();
        txtCustAddr = new javax.swing.JTextField();
        lblCustZip = new javax.swing.JLabel();
        txtCustZip = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblCustPhoto = new javax.swing.JLabel();
        btnCustPhotoUpload = new javax.swing.JButton();
        lblAddCust = new javax.swing.JButton();
        pwCustPass = new javax.swing.JPasswordField();

        lblAddCustomer.setText("Add Customer");

        lblCustName.setText("Enter Full Name :");

        lblCustUserName.setText("Set Username :");

        lblCustPass.setText("Set Password :");

        lblCustContact.setText("Enter Contact No :");

        lblCustEmail.setText("Enter Email ID:");

        pbCustPassStr.setMaximum(30);
        pbCustPassStr.setMinimum(1);
        pbCustPassStr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pbCustPassStrStateChanged(evt);
            }
        });

        lblCustAddr.setText("Enter Street Address :");

        lblCustZip.setText("Enter Zip Code :");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCustPhoto.setBackground(new java.awt.Color(222, 236, 236));
        lblCustPhoto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCustPhoto.setForeground(new java.awt.Color(0, 102, 102));
        lblCustPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCustPhotoUpload.setBackground(new java.awt.Color(222, 236, 236));
        btnCustPhotoUpload.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCustPhotoUpload.setForeground(new java.awt.Color(0, 102, 102));
        btnCustPhotoUpload.setText("Upload");
        btnCustPhotoUpload.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        btnCustPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustPhotoUploadActionPerformed(evt);
            }
        });

        lblAddCust.setText("Add");
        lblAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAddCustActionPerformed(evt);
            }
        });

        pwCustPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwCustPassActionPerformed(evt);
            }
        });
        pwCustPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwCustPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwCustPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustUserName)
                    .addComponent(lblCustName)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustContact)
                            .addComponent(lblCustPass)
                            .addComponent(lblCustEmail)
                            .addComponent(lblCustAddr)
                            .addComponent(lblCustZip))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddCustomer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCustAddr)
                            .addComponent(pbCustPassStr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCustUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustContact, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustZip, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(pwCustPass))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCustPhotoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(118, 118, 118)
                .addComponent(lblAddCust)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblCustPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnCustPhotoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAddCustomer)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustName)
                            .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustUserName)
                            .addComponent(txtCustUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustPass)
                            .addComponent(pwCustPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbCustPassStr, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustContact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustEmail)
                            .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustAddr)
                            .addComponent(txtCustAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustZip)
                            .addComponent(txtCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblAddCust))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustPhotoUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);

        BufferedImage bfImage = null;
        try {
            File fileImage = fileChooser.getSelectedFile();
            bfImage = ImageIO.read(new File(fileImage.getAbsolutePath()));
        } catch (IOException ex) {
            Logger.getLogger(AddCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image imPhoto = bfImage.getScaledInstance(lblCustPhoto.getWidth(), lblCustPhoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imIcon = new ImageIcon(imPhoto);
       
        lblCustPhoto.setIcon(imIcon);
        cust.setCustPhoto(imPhoto);

    }//GEN-LAST:event_btnCustPhotoUploadActionPerformed

    private void lblAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAddCustActionPerformed
        // TODO add your handling code here:
        
        String custName = txtCustName.getText();
        String custContact = txtCustContact.getText();
        String custAddr = txtCustAddr.getText();
        String custZipCode = txtCustZip.getText();
        String custUserName = txtCustUserName.getText();
        String custPass = String.valueOf(pwCustPass.getPassword());
        String custEmail = txtCustEmail.getText();
     
        if( custName.isEmpty() || custContact.isEmpty() || custAddr.isEmpty() || custZipCode.isEmpty() ||
                custUserName.isEmpty() || custPass.isEmpty() || custEmail.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(custContact)) {
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }   else if (!system.validateEmail(custEmail)) {
            JOptionPane.showMessageDialog(null, "Kindly check the entered Email ID format.");
        }   else if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(custUserName)) {
            JOptionPane.showMessageDialog(null, "Entered User Name is already mapped to another Customer");    
        }   else if (!custDirectory.isEmailUnique(custEmail)) {
            JOptionPane.showMessageDialog(null, "Entered Email ID is already mapped to another Customer.");
        }   else if (!custDirectory.isContactNoUnique(custContact)) {
            JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Customer.");
        }   else {
        
            cust.setCustID(custDirectory.genCustID() );
            cust.setCustName(custName);
            cust.setCustAddr(custAddr);
            cust.setCustContact(custContact);
            cust.setCustEmail(custEmail);
            cust.setCustZipCode(custZipCode);
            custDirectory.addCustomer(cust);
            Employee employee = system.getEmployeeDirectory().createEmployee(cust.getCustID());
            system.setCustomerDirectory(custDirectory);
             UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new CustomerRole());
            JOptionPane.showMessageDialog(null, "New Customer "+account.getUsername()+" added to the System Successfully!");
            resetFields();
        }
    }//GEN-LAST:event_lblAddCustActionPerformed
   public void resetFields() {
        txtCustAddr.setText("");
        txtCustContact.setText("");
        txtCustEmail.setText("");
        txtCustName.setText("");
        pwCustPass.setText("");
        txtCustUserName.setText("");
        txtCustZip.setText("");
        pbCustPassStr.setValue(0);
        lblCustPhoto.setText("");
    }
    private void pbCustPassStrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pbCustPassStrStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pbCustPassStrStateChanged

    private void pwCustPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwCustPassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pwCustPassActionPerformed

    private void pwCustPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwCustPassKeyTyped
        // TODO add your handling code here:
        int pwSize = pwCustPass.getText().length();
//        System.out.println("PassKeyTyped PwSize :: "+pwSize);
        pbCustPassStr.setValue(pwSize);
    }//GEN-LAST:event_pwCustPassKeyTyped

    private void pwCustPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwCustPassKeyReleased
        // TODO add your handling code here:
//          int pwSize = pwCustPass.getText().length();
//        System.out.println("PassKeyReleased PwSize :: "+pwSize);
//        pbCustPassStr.setValue(pwSize);
    }//GEN-LAST:event_pwCustPassKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCustomersJPanel manageCustomersJPanel = (ManageCustomersJPanel) component;
        manageCustomersJPanel.populateCustomerListTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCustPhotoUpload;
    private javax.swing.JButton lblAddCust;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblCustAddr;
    private javax.swing.JLabel lblCustContact;
    private javax.swing.JLabel lblCustEmail;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblCustPass;
    private javax.swing.JLabel lblCustPhoto;
    private javax.swing.JLabel lblCustUserName;
    private javax.swing.JLabel lblCustZip;
    private javax.swing.JProgressBar pbCustPassStr;
    private javax.swing.JPasswordField pwCustPass;
    private javax.swing.JTextField txtCustAddr;
    private javax.swing.JTextField txtCustContact;
    private javax.swing.JTextField txtCustEmail;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustUserName;
    private javax.swing.JTextField txtCustZip;
    // End of variables declaration//GEN-END:variables
}
