/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InfraRole;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class InfraRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfraRequestJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final EcoSystem business;
    public InfraRequestJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        initComponents();
        populateOrderListTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        public void populateOrderListTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrderList.getModel();
        model.setRowCount(0);
        
    } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestWorkList = new javax.swing.JLabel();
        scrollOrderList = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();
        brnConfirmOrder = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        brnConfirmOrder1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(0, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestWorkList.setBackground(new java.awt.Color(204, 255, 255));
        lblRestWorkList.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblRestWorkList.setForeground(new java.awt.Color(0, 51, 51));
        lblRestWorkList.setText("Event Equipment Requests");
        add(lblRestWorkList, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 24, -1, -1));

        tblOrderList.setBackground(new java.awt.Color(204, 204, 255));
        tblOrderList.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        tblOrderList.setForeground(new java.awt.Color(0, 51, 51));
        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order No", "Org Name", "Equipment Name", "Quantity", "Order Status", "Deliver To", "Location Team Messageg", "Order By", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollOrderList.setViewportView(tblOrderList);

        add(scrollOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 843, 110));

        brnConfirmOrder.setBackground(new java.awt.Color(204, 255, 255));
        brnConfirmOrder.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        brnConfirmOrder.setForeground(new java.awt.Color(0, 51, 51));
        brnConfirmOrder.setText("Reject Request");
        brnConfirmOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        brnConfirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnConfirmOrderActionPerformed(evt);
            }
        });
        add(brnConfirmOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 110, 30));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 50, 30));

        brnConfirmOrder1.setBackground(new java.awt.Color(204, 255, 255));
        brnConfirmOrder1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        brnConfirmOrder1.setForeground(new java.awt.Color(0, 51, 51));
        brnConfirmOrder1.setText("Approve Request");
        brnConfirmOrder1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        brnConfirmOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnConfirmOrder1ActionPerformed(evt);
            }
        });
        add(brnConfirmOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void brnConfirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnConfirmOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnConfirmOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnBackActionPerformed

    private void brnConfirmOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnConfirmOrder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnConfirmOrder1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnConfirmOrder;
    private javax.swing.JButton brnConfirmOrder1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblRestWorkList;
    private javax.swing.JScrollPane scrollOrderList;
    private javax.swing.JTable tblOrderList;
    // End of variables declaration//GEN-END:variables
}
