/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnterAdminRole;

import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class GeoInfraManageOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VoluntaryOperatingUnitOrganizationJPanel
     */
    private final OrganizationDirectory directory;

    public GeoInfraManageOrgJPanel(OrganizationDirectory directory) {
        initComponents();
        this.directory = directory;
        volPopulate();
        populateOrganizationTypeComboBox();

    }

    private void populateOrganizationTypeComboBox() {
        OrganizationTypeComboBox.removeAllItems();
        OrganizationTypeComboBox.addItem(Organization.Type.Location);
        OrganizationTypeComboBox.addItem(Organization.Type.Infrastructure);
    }

    public void volPopulate() {
        DefaultTableModel model = (DefaultTableModel) tblOrgList.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            {
                Object[] row = new Object[2];
                row[0] = organization.getType().getValue();
                row[1] = organization.getName();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrgList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        OrganizationTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        organizationName = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1058, 840));
        setPreferredSize(new java.awt.Dimension(1058, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrgList.setBackground(new java.awt.Color(204, 204, 255));
        tblOrgList.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblOrgList.setForeground(new java.awt.Color(25, 56, 82));
        tblOrgList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Type", "Organization Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrgList.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(tblOrgList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 595, 250));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE GEO INFRA ORGANIZATIONS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 595, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Organization Type ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        OrganizationTypeComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        OrganizationTypeComboBox.setForeground(new java.awt.Color(25, 56, 82));
        add(OrganizationTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 171, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setText("Organization Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        organizationName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        organizationName.setForeground(new java.awt.Color(25, 56, 82));
        add(organizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 171, -1));

        addJButton.setBackground(new java.awt.Color(255, 255, 255));
        addJButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addJButton.setForeground(new java.awt.Color(25, 56, 82));
        addJButton.setText("Add Organization");
        addJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) OrganizationTypeComboBox.getSelectedItem();

        if ("".equals(organizationName.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        } else {
            Organization organization = directory.createOrganization(type, organizationName.getText());
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            organizationName.setText("");
            volPopulate();
        }

    }//GEN-LAST:event_addJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrganizationTypeComboBox;
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField organizationName;
    private javax.swing.JTable tblOrgList;
    // End of variables declaration//GEN-END:variables
}
