/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HostRole;

import Business.EcoSystem;
import Business.Host.Host;
import Business.Host.HostDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saivignesh Sridhar
 */
public class ViewUpdateHostJPanel extends javax.swing.JPanel {

    
    
    public HostDirectory hostDirectory;
    public JPanel container;
    public Host host;
    private final EcoSystem system;
    private String currentPhoneNo;
    private String currentMailID;
    
    public ViewUpdateHostJPanel(EcoSystem system, JPanel container, Host host, HostDirectory hostDirectory) {
        
        initComponents();
        this.hostDirectory = hostDirectory;
        this.container = container;
        this.host = host;
        this.system = system;
        this.currentMailID = host.getHostEmail();
        this.currentPhoneNo = host.getHostContact(); 
        
        txtHostID.setText(host.getHostID());
        txtHostAddr.setText(host.getHostAddr());
        txtHostContact.setText(host.getHostContact());
        txtHostEmail.setText(host.getHostEmail());
        txtHostName.setText(host.getHostName());
        txtHostZip.setText(host.getHostZipCode());
        Image imPhoto = host.getHostPhoto();
        if(imPhoto!=null){
        ImageIcon imIcon = new ImageIcon(imPhoto);
        lblHostPhoto.setIcon(imIcon);
        }
        disableEdit();
    }
private void disableEdit(){
    txtHostID.setEditable(false);
    txtHostAddr.setEditable(false);
    txtHostContact.setEditable(false);
    txtHostEmail.setEditable(false);
    txtHostName.setEditable(false);
    txtHostZip.setEditable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHostPhoto = new javax.swing.JLabel();
        btnHostPhotoUpload = new javax.swing.JButton();
        txtHostContact = new javax.swing.JTextField();
        lblHostEmail = new javax.swing.JLabel();
        txtHostEmail = new javax.swing.JTextField();
        lblViewUpdateCust = new javax.swing.JLabel();
        lblHostAddr = new javax.swing.JLabel();
        lblHostName = new javax.swing.JLabel();
        txtHostAddr = new javax.swing.JTextField();
        lblHostZip = new javax.swing.JLabel();
        txtHostZip = new javax.swing.JTextField();
        lblHostContact = new javax.swing.JLabel();
        txtHostName = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnEnableUpdate = new javax.swing.JButton();
        lblHostID = new javax.swing.JLabel();
        txtHostID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));

        lblHostPhoto.setBackground(new java.awt.Color(204, 255, 255));
        lblHostPhoto.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostPhoto.setForeground(new java.awt.Color(0, 51, 51));
        lblHostPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHostPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHostPhotoUpload.setBackground(new java.awt.Color(204, 255, 255));
        btnHostPhotoUpload.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnHostPhotoUpload.setForeground(new java.awt.Color(0, 51, 51));
        btnHostPhotoUpload.setText("Upload");
        btnHostPhotoUpload.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHostPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHostPhotoUploadActionPerformed(evt);
            }
        });

        txtHostContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostContact.setForeground(new java.awt.Color(0, 51, 51));

        lblHostEmail.setBackground(new java.awt.Color(204, 255, 255));
        lblHostEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostEmail.setForeground(new java.awt.Color(0, 51, 51));
        lblHostEmail.setText("Email ID:");

        txtHostEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostEmail.setForeground(new java.awt.Color(0, 51, 51));

        lblViewUpdateCust.setBackground(new java.awt.Color(204, 255, 255));
        lblViewUpdateCust.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblViewUpdateCust.setForeground(new java.awt.Color(0, 51, 51));
        lblViewUpdateCust.setText("Host Details");

        lblHostAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblHostAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblHostAddr.setText("Street Address :");

        lblHostName.setBackground(new java.awt.Color(204, 255, 255));
        lblHostName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostName.setForeground(new java.awt.Color(0, 51, 51));
        lblHostName.setText("Full Name :");

        txtHostAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostAddr.setForeground(new java.awt.Color(0, 51, 51));

        lblHostZip.setBackground(new java.awt.Color(204, 255, 255));
        lblHostZip.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostZip.setForeground(new java.awt.Color(0, 51, 51));
        lblHostZip.setText("Zip Code :");

        txtHostZip.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostZip.setForeground(new java.awt.Color(0, 51, 51));

        lblHostContact.setBackground(new java.awt.Color(204, 255, 255));
        lblHostContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostContact.setForeground(new java.awt.Color(0, 51, 51));
        lblHostContact.setText("Contact No :");

        txtHostName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostName.setForeground(new java.awt.Color(0, 51, 51));

        btnBack1.setBackground(new java.awt.Color(204, 255, 255));
        btnBack1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 51, 51));
        btnBack1.setText("Back");
        btnBack1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnSaveChanges.setBackground(new java.awt.Color(204, 255, 255));
        btnSaveChanges.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnSaveChanges.setForeground(new java.awt.Color(0, 51, 51));
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnEnableUpdate.setBackground(new java.awt.Color(204, 255, 255));
        btnEnableUpdate.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnEnableUpdate.setForeground(new java.awt.Color(0, 51, 51));
        btnEnableUpdate.setText("Enable Update");
        btnEnableUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnableUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUpdateActionPerformed(evt);
            }
        });

        lblHostID.setBackground(new java.awt.Color(204, 255, 255));
        lblHostID.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblHostID.setForeground(new java.awt.Color(0, 51, 51));
        lblHostID.setText("Host ID :");

        txtHostID.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtHostID.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewUpdateCust)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(110, 110, 110)
                                    .addComponent(lblHostEmail))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHostID, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHostName, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHostContact, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHostID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHostContact, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHostEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEnableUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHostAddr)
                                        .addComponent(lblHostZip))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHostAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHostZip, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnHostPhotoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblHostPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblViewUpdateCust)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblHostContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHostID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHostID))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHostName))
                                .addGap(7, 7, 7)
                                .addComponent(txtHostContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHostEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHostEmail))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHostAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHostAddr))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHostZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHostZip)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHostPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnHostPhotoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(btnEnableUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack1)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHostPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHostPhotoUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);

        BufferedImage bfImage = null;
        try {
            File fileImage = fileChooser.getSelectedFile();
            bfImage = ImageIO.read(new File(fileImage.getAbsolutePath()));
        } catch (IOException ex) {
            Logger.getLogger(AddHostJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image imPhoto = bfImage.getScaledInstance(lblHostPhoto.getWidth(), lblHostPhoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon imIcon = new ImageIcon(imPhoto);

        lblHostPhoto.setIcon(imIcon);
        host.setHostPhoto(imPhoto);
    }//GEN-LAST:event_btnHostPhotoUploadActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageHostJPanel manageHostJPanel = (ManageHostJPanel) component;
        manageHostJPanel.populateHostListTable();

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
       
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        String hostID = txtHostID.getText();
        String hostName = txtHostName.getText();
        String hostContact = txtHostContact.getText();
        String hostAddr = txtHostAddr.getText();
        String hostZipCode = txtHostZip.getText();
        String hostEmail = txtHostEmail.getText();
        boolean allSet = true;
        
        if( hostName.isEmpty() || hostContact.isEmpty() || hostAddr.isEmpty() || hostZipCode.isEmpty() || hostEmail.isEmpty() ) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!system.validateMobileNo(hostContact)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        }   else if (!system.validateEmail(hostEmail)) {
            allSet = false;
            JOptionPane.showMessageDialog(null, "Kindly check the entered Email ID format.");
        }   else if (!hostDirectory.isEmailUnique(hostEmail)) {
            if(!currentMailID.equals(currentMailID))
            {
                allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Email ID is already mapped to another Host.");
            }
        }
        if (!hostDirectory.isContactNoUnique(hostContact)) {
            if(!currentPhoneNo.equals(hostContact)){
                 allSet = false;
                JOptionPane.showMessageDialog(null, "Entered Contact No is already mapped to another Host.");
            }
        }
        if(allSet == true){
            hostDirectory.updateHost(hostID, hostName, hostContact, hostAddr, hostZipCode, hostEmail);
            JOptionPane.showMessageDialog(null, "Host details updated!");
            disableEdit();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnEnableUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUpdateActionPerformed
        // TODO add your handling code here:
    txtHostAddr.setEditable(true);
    txtHostContact.setEditable(true);
    txtHostEmail.setEditable(true);
    txtHostName.setEditable(true);
    txtHostZip.setEditable(true);
    btnEnableUpdate.setEnabled(false);
    }//GEN-LAST:event_btnEnableUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnEnableUpdate;
    private javax.swing.JButton btnHostPhotoUpload;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel lblHostAddr;
    private javax.swing.JLabel lblHostContact;
    private javax.swing.JLabel lblHostEmail;
    private javax.swing.JLabel lblHostID;
    private javax.swing.JLabel lblHostName;
    private javax.swing.JLabel lblHostPhoto;
    private javax.swing.JLabel lblHostZip;
    private javax.swing.JLabel lblViewUpdateCust;
    private javax.swing.JTextField txtHostAddr;
    private javax.swing.JTextField txtHostContact;
    private javax.swing.JTextField txtHostEmail;
    private javax.swing.JTextField txtHostID;
    private javax.swing.JTextField txtHostName;
    private javax.swing.JTextField txtHostZip;
    // End of variables declaration//GEN-END:variables
}
